name: Cron ‐ Expire Bets

# on:
#   schedule:
#     - cron: "2/5 * * * *"

on:
  workflow_dispatch:

jobs:
  expire_bets_job:
    runs-on: ubuntu-latest
    steps:
      - name: Call Next.js expire-bets endpoint
        run: |
          curl -s \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            "${{ vars.CRON_URL_PROTOCOL }}://${{ vars.CRON_URL_DOMAIN }}/api/expire-bets"
